### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Blackmadman** [wyatt-herkamp/DynmapEssentials#23]
Hi, this message comes up every time the plugin updates and spams the console.
Paper 1.20.6
Dynmap latest version
EssentialsX latest version

[14:11:57 WARN]: [DynmapEssentials] Task #53 for DynmapEssentials v1.3 generated an exception
java.lang.NullPointerException: Cannot invoke "org.dynmap.markers.Marker.setLocation(String, double, double, double)" because "it" is null
        at DynmapEssentials-1.3-all.jar/dev.kingtux.dynmapessentials.MarkerUpdater.updateHomes(MarkerUpdater.kt:109) ~[DynmapEssentials-1.3-all.jar:?]
        at DynmapEssentials-1.3-all.jar/dev.kingtux.dynmapessentials.MarkerUpdater.run(MarkerUpdater.kt:128) ~[DynmapEssentials-1.3-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by wyatt-herkamp** [comment]
Try running the latest GitHub actions build. I am pretty this is patched just haven't updated

**Comment by Blackmadman** [comment]
And how do I get to it? I'm not familiar with GitHub. Is there a download link?

**Comment by Blackmadman** [comment]
Now the errors are gone, thanks for the quick help. Great work.

**Comment by brest21** [comment]
Same issue; Having trouble with the artifact download as it says expired. Thanks.

**Comment by wyatt-herkamp** [comment]
Sorry. I have been busy. I will get this handled give me 30 minutes
